FROM node:20-alpine
WORKDIR /app

# 1. Először a csomagokat másoljuk és telepítjük
COPY package*.json ./
RUN npm install

# 2. Utána bemásoljuk a teljes kódot
COPY . .

# 3. Kinyitjuk a 4200-as portot
EXPOSE 4200

# 4. Elindítjuk az Angulart a felhőre optimalizálva
CMD ["npx", "ng", "serve", "--host", "0.0.0.0", "--disable-host-check"]